# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "Client": "01_client.ipynb",
         "Jobs": "02_jobs.ipynb",
         "log_request": "03_api.ipynb",
         "API": "03_api.ipynb",
         "logger": "03_api.ipynb",
         "default_headers": "03_api.ipynb",
         "Authenticate": "04_authenticate.ipynb",
         "Files": "05_files.ipynb",
         "Workflows": "06_workflows.ipynb"}

modules = ["core.py",
           "client.py",
           "jobs.py",
           "api.py",
           "authenticate.py",
           "files.py",
           "workflows.py"]

doc_url = "https://jesseclarkayx.github.io/yx_motor/"

git_url = "https://github.com/jesseclarkayx/yx_motor/tree/master/"

def custom_doc_links(name):
    return None
