# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Client": "01_client.ipynb",
         "Jobs": "02_jobs.ipynb",
         "log_request": "03_api.ipynb",
         "API": "03_api.ipynb",
         "logger": "03_api.ipynb",
         "default_headers": "03_api.ipynb",
         "Authenticate": "04_authenticate.ipynb",
         "Files": "05_files.ipynb",
         "Workflows": "06_workflows.ipynb",
         "seed_workflow": "integration_tests.ipynb",
         "scaffold_workflows_integration_tests": "integration_tests.ipynb",
         "fetch_all_jobs": "integration_tests.ipynb",
         "test_can_get_jobs_with_no_args": "integration_tests.ipynb",
         "test_that_server_has_jobs_available": "integration_tests.ipynb",
         "test_can_get_job_by_id": "integration_tests.ipynb",
         "test_get_log_functionality": "integration_tests.ipynb",
         "test_cancel_job_functionality": "integration_tests.ipynb"}

modules = ["client.py",
           "jobs.py",
           "api.py",
           "authenticate.py",
           "files.py",
           "workflows.py",
           "int_test_helpers.py"]

doc_url = "https://jesseclarkayx.github.io/yx_motor/"

git_url = "https://github.com/jesseclarkayx/yx_motor/tree/master/"

def custom_doc_links(name):
    return None
