# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Jesse-Clarkayx.github.io/yx_motor/"

git_url = "https://github.com/Jesse-Clarkayx/yx_motor/tree/master/"

def custom_doc_links(name): return None
