# AUTOGENERATED! DO NOT EDIT! File to edit: 01_client.ipynb (unless otherwise specified).

__all__ = ['Client']

# Cell
import requests

from .api import API
from .authenticate import Authenticate
from .jobs import Jobs


class Client:
    "Wrapper for Alteryx Server API."

    def __init__(self, base_url: str, login_email: str, login_pwd: str):
        """Initialize a yx_motor client object."""
        self.base_url = base_url
        self.api_url = f"{base_url}api/v1/"

        self.auth_endpoint = "authenticate"

        self.login_email = login_email
        self.login_pwd = login_pwd

        self.headers = {
            "Content-Type": "application/json",
            "Accept": "*/*",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip,deflate",
        }

        self.api = API(api_url=self.api_url, headers=self.headers)

        self.authenticate = Authenticate(self.api)
        self.jobs = Jobs(self.api)

        self.authenticate.authenticate(
            login_email=self.login_email, login_pwd=self.login_pwd
        )

    def get_users(self):
        response = self.api.get("users")
        return response