# AUTOGENERATED! DO NOT EDIT! File to edit: 01_motor.ipynb (unless otherwise specified).

__all__ = ['Motor']

# Cell
import requests

class Motor:
    "Wrapper for Alteryx Server API."

    def __init__(self,
                 base_url: str,
                 login_email: str,
                 login_pwd: str):

        self.base_url = base_url
        self.api_url = f"{base_url}api/v1/"

        self.auth_endpoint = "authenticate"

        self.login_email = login_email
        self.login_pwd = login_pwd

        self.headers = {
            "Content-Type": "application/json",
            "Accept": "*/*",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip,deflate"
        }

        self.api = API(api_url=self.api_url,
                       headers=self.headers)

        self.jobs = Jobs(self.api)

        self.is_authenticated = False
        self.authenticate()


    def authenticate(self) -> requests.Response:
        payload = {
            "email": self.login_email,
            "password": self.login_pwd
        }
        response = self.api.post(url=self.auth_endpoint,
                                 json=payload)
        if response.status_code == 200:
            self.api.jar.update(response.cookies)
            self.is_authenticated = True
        return response

    def get_users(self):
        response = self.api.get("users")
        return response
